#!/bin/sh

while read local_ref local_sha remote_ref remote_sha
do
  for commit in $(git rev-list --reverse $remote_sha..$local_sha)
  do
    if ! git verify-commit $commit >/dev/null 2>&1
    then
      echo "ERROR: Unsigned commit ${commit} detected! All commits must be signed and verified."
      exit 1
    fi
  done
done
